# # This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# # See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   node: circleci/node@4.7

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   sample: # This is the name of the workflow, feel free to change it to better match your workflow.
#     # Inside the workflow, you define the jobs you want to run.
#     jobs:
#       - node/test:
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
#           version: '16.10'
#           # If you are using yarn, change the line below from "npm" to "yarn"
#           pkg-manager: npm

# version: 2.1
#   orbs:
#     apex: circleci/salesforce-apex@x.y
#   jobs:
#     install_authenticate:
#       docker:
#         - image: cimg/node:14.5
#       steps:
#         - checkout
#         - apex/setup:
#            defaultusername: user@email.com
#         - run:
#             name: Run your SFDX commands here
#             command: |
#               echo "You now have access to the sfdx cli and may execute commands against it. https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm"
#   workflows:
#     basic-test:
#       jobs:
#         - install_authenticate
version: 1
# working_directory: ~/sfdx-example0
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # - run:
      #     name: Install Dependencies
      #     command: . build/install.sh
      # - run:
      #     name: Create Scracth Org
      #     command: . build/createScractchOrg.sh
      # - run:
      #     name: Validate Components & Run Tests
      #     command: . build/test.sh
      # - store_test_results:
      #     path: testResults
      - run:
          name: Deploy
          command: . build/deployProdOrg.sh